---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5c87f9104784af001237733b/webhook/forestry
sections:
- type: document
  path: site-metadata.json
  label: Config
  templates:
  - config
- type: document
  path: src/pages/index.md
  label: Home
  templates:
  - home
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
  exclude: "{index.md,elements.md}"
  templates:
  - page
- type: document
  path: src/pages/elements.md
  label: Elements
  templates:
  - elements
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gatsby build
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
